version: '3'

services:
    app:
        image: opensourcefoundries/leshan:latest
        ports:
            - "8080:8080"
            - "5683:5683/udp"
            - "5684:5684/udp"
            - "5685:5685/udp"
        restart: always
